
-- Insert new permission keys for all configurable roles
-- Using ON CONFLICT to avoid duplicates with existing keys

-- Helper: insert permission for a role+key combo
INSERT INTO public.role_permissions (role, permission_key, is_enabled)
VALUES
-- ============ branch_manager (all enabled) ============
('branch_manager', 'finance_pl', true),
('branch_manager', 'finance_cash', true),
('branch_manager', 'finance_ar', true),
('branch_manager', 'finance_ap', true),
('branch_manager', 'hr', true),
('branch_manager', 'payroll', true),
('branch_manager', 'equipment', true),
('branch_manager', 'room_assignments', true),
('branch_manager', 'visa', true),
('branch_manager', 'manasik', true),
('branch_manager', 'haji', true),
('branch_manager', 'itinerary_templates', true),
('branch_manager', 'savings', true),
('branch_manager', 'loyalty', true),
('branch_manager', 'referrals', true),
('branch_manager', 'coupons', true),
('branch_manager', 'appearance', true),
('branch_manager', 'static_pages', true),
('branch_manager', 'testimonials', true),
('branch_manager', 'marketing_materials', true),
('branch_manager', 'offline_content', true),
('branch_manager', 'whatsapp', true),
('branch_manager', 'support_tickets', true),
('branch_manager', 'security_audit', false),
('branch_manager', '2fa', false),
('branch_manager', 'branches', true),
('branch_manager', 'document_verification', true),
('branch_manager', 'document_generator', true),

-- ============ finance ============
('finance', 'finance_pl', true),
('finance', 'finance_cash', true),
('finance', 'finance_ar', true),
('finance', 'finance_ap', true),
('finance', 'hr', false),
('finance', 'payroll', true),
('finance', 'equipment', false),
('finance', 'room_assignments', false),
('finance', 'visa', false),
('finance', 'manasik', false),
('finance', 'haji', false),
('finance', 'itinerary_templates', false),
('finance', 'savings', true),
('finance', 'loyalty', false),
('finance', 'referrals', false),
('finance', 'coupons', false),
('finance', 'appearance', false),
('finance', 'static_pages', false),
('finance', 'testimonials', false),
('finance', 'marketing_materials', false),
('finance', 'offline_content', false),
('finance', 'whatsapp', false),
('finance', 'support_tickets', false),
('finance', 'security_audit', false),
('finance', '2fa', false),
('finance', 'branches', false),
('finance', 'document_verification', false),
('finance', 'document_generator', false),

-- ============ sales ============
('sales', 'finance_pl', false),
('sales', 'finance_cash', false),
('sales', 'finance_ar', false),
('sales', 'finance_ap', false),
('sales', 'hr', false),
('sales', 'payroll', false),
('sales', 'equipment', false),
('sales', 'room_assignments', false),
('sales', 'visa', false),
('sales', 'manasik', true),
('sales', 'haji', true),
('sales', 'itinerary_templates', false),
('sales', 'savings', true),
('sales', 'loyalty', true),
('sales', 'referrals', true),
('sales', 'coupons', true),
('sales', 'appearance', false),
('sales', 'static_pages', false),
('sales', 'testimonials', false),
('sales', 'marketing_materials', false),
('sales', 'offline_content', false),
('sales', 'whatsapp', true),
('sales', 'support_tickets', true),
('sales', 'security_audit', false),
('sales', '2fa', false),
('sales', 'branches', false),
('sales', 'document_verification', false),
('sales', 'document_generator', false),

-- ============ marketing ============
('marketing', 'finance_pl', false),
('marketing', 'finance_cash', false),
('marketing', 'finance_ar', false),
('marketing', 'finance_ap', false),
('marketing', 'hr', false),
('marketing', 'payroll', false),
('marketing', 'equipment', false),
('marketing', 'room_assignments', false),
('marketing', 'visa', false),
('marketing', 'manasik', false),
('marketing', 'haji', false),
('marketing', 'itinerary_templates', false),
('marketing', 'savings', false),
('marketing', 'loyalty', true),
('marketing', 'referrals', true),
('marketing', 'coupons', true),
('marketing', 'appearance', true),
('marketing', 'static_pages', true),
('marketing', 'testimonials', true),
('marketing', 'marketing_materials', true),
('marketing', 'offline_content', false),
('marketing', 'whatsapp', true),
('marketing', 'support_tickets', false),
('marketing', 'security_audit', false),
('marketing', '2fa', false),
('marketing', 'branches', false),
('marketing', 'document_verification', false),
('marketing', 'document_generator', false),

-- ============ operational ============
('operational', 'finance_pl', false),
('operational', 'finance_cash', false),
('operational', 'finance_ar', false),
('operational', 'finance_ap', false),
('operational', 'hr', false),
('operational', 'payroll', false),
('operational', 'equipment', true),
('operational', 'room_assignments', true),
('operational', 'visa', true),
('operational', 'manasik', true),
('operational', 'haji', true),
('operational', 'itinerary_templates', true),
('operational', 'savings', false),
('operational', 'loyalty', false),
('operational', 'referrals', false),
('operational', 'coupons', false),
('operational', 'appearance', false),
('operational', 'static_pages', false),
('operational', 'testimonials', false),
('operational', 'marketing_materials', false),
('operational', 'offline_content', true),
('operational', 'whatsapp', false),
('operational', 'support_tickets', true),
('operational', 'security_audit', false),
('operational', '2fa', false),
('operational', 'branches', false),
('operational', 'document_verification', true),
('operational', 'document_generator', true),

-- ============ equipment ============
('equipment', 'finance_pl', false),
('equipment', 'finance_cash', false),
('equipment', 'finance_ar', false),
('equipment', 'finance_ap', false),
('equipment', 'hr', false),
('equipment', 'payroll', false),
('equipment', 'equipment', true),
('equipment', 'room_assignments', false),
('equipment', 'visa', false),
('equipment', 'manasik', false),
('equipment', 'haji', false),
('equipment', 'itinerary_templates', false),
('equipment', 'savings', false),
('equipment', 'loyalty', false),
('equipment', 'referrals', false),
('equipment', 'coupons', false),
('equipment', 'appearance', false),
('equipment', 'static_pages', false),
('equipment', 'testimonials', false),
('equipment', 'marketing_materials', false),
('equipment', 'offline_content', false),
('equipment', 'whatsapp', false),
('equipment', 'support_tickets', false),
('equipment', 'security_audit', false),
('equipment', '2fa', false),
('equipment', 'branches', false),
('equipment', 'document_verification', false),
('equipment', 'document_generator', false)
ON CONFLICT (role, permission_key) DO NOTHING;
